---
format: dashboard
theme: [cosmo, theme.scss]
preview:
  port: 4200
---

```{r}
#| label: setup

library(tidyverse)
library(redivis)

.font <- "Whitney"
theme_set(theme_bw(base_size = 14, base_family = .font))
theme_update(panel.grid = element_blank(),
             strip.background = element_blank(),
             legend.key = element_blank(),
             panel.border = element_blank(),
             axis.line = element_line(),
             strip.text = element_text(face = "bold"))

pal <- list(primary = "#f7ca69", secondary = "#69F7CA", tertiary = "#CA69F7",
            light = "#9c9c9c")
```

```{r}
#| label: load-data

runs_processed <- redivis$user("mikabr")$
  workflow("pilot_summary")$
  table("runs_processed")$
  to_tibble()

runs <- runs_processed |>
  mutate(site = dataset |> str_remove("_pilot") |> fct_infreq(),
         task_id = task_id |> fct_infreq())
```

```{r}
#| label: all-values

display_vals <- list(
  n_sites = runs |> distinct(site) |> nrow(),
  n_tasks = runs |> distinct(task_id) |> nrow(),
  n_users = runs |> distinct(user_id) |> nrow(),
  n_runs = runs |> distinct(user_id, run_id) |> nrow()
)
```

## Row {height="25%"}

```{r}
#| content: valuebox
#| title: "Sites"

list(
  icon = "globe",
  color = pal$secondary,
  value = display_vals$n_sites
)
```

```{r}
#| content: valuebox
#| title: "Participants"

list(
  icon = "person-arms-up",
  color = pal$primary,
  value = display_vals$n_users
)
```

```{r}
#| content: valuebox
#| title: "Assessments"

list(
  icon = "clipboard-data",
  color = pal$tertiary,
  value = display_vals$n_runs
)
```

## Row {height="75%"}

### Column {width="50%"}

### Row {.tabset}

```{r}
#| title: "Participants by site"

ggplot(runs |> distinct(site, user_id), aes(y = site)) +
  geom_bar(fill = pal$primary) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "Number of participants", y = "")
```

```{r}
#| title: "Assessments by site"

ggplot(runs |> distinct(site, run_id), aes(y = site)) +
  geom_bar(fill = pal$tertiary) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "Number of assessments", y = "")
```

```{r}
#| title: "Ages by site"

ggplot(runs, aes(x = age, fill = site)) +
  geom_histogram(binwidth = 1) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "Age (years)", y = "Number of assessments")
```

### Column {width="50%"}

### Row {.tabset}

```{r}
#| title: "Participants by task"

ggplot(runs |> distinct(task_id, user_id), aes(y = task_id)) +
  geom_bar(fill = pal$primary) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "Number of participants", y = "")
```

```{r}
#| title: "Assessments by task"

ggplot(runs |> distinct(task_id, run_id), aes(y = task_id)) +
  geom_bar(fill = pal$tertiary) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "Number of assessments", y = "")
```

```{r}
#| title: "Ages by task"

ggplot(runs, aes(x = age, fill = task_id)) +
  geom_histogram(binwidth = 1) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "Age (years)", y = "Number of assessments")
```
